image: docker:latest

services:
- docker:dind

before_script:
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/pdouelle/ci-build

stages:
  - build

build:
  stage: build
  script:
     - docker-compose -f docker-compose.ci.build.yml up
     - docker-compose -f docker-compose.ci.build.yml push $CONTAINER_TEST_IMAGE