image: docker:latest

services:
- docker:dind

before_script:
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/pdouelle/webapplication1:$CI_BUILD_REF_NAME

stages:
  - build

build:
  stage: build
  script:
     - docker-compose -f docker-compose.ci.build.yml up
     - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
     - docker-compose -f docker-compose.ci.build.yml push $CONTAINER_TEST_IMAGE