image: docker:latest

services:
- docker:dind

variables:
    CONTAINER_IMAGE: $CI_REGISTRY/pdouelle/webapplication1:$CI_BUILD_REF_NAME

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
    - docker version
    - docker-compose version
    - docker-compose -f docker-compose.ci.build.yml up
    - export TAG=$CI_BUILD_REF_NAME
    - docker-compose build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_IMAGE

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - master
  script:
    - upgrade --environment $RANCHER_ENV --stack $RANCHER_STACK --service $RANCHER_SERVICE --no-start-before-stopping --no-wait-for-upgrade-to-finish