version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    environment:
      - DOCKER_HOST=127.0.0.1:80
    volumes:
      - ./workspace/WebApplication1:/src:rw
    working_dir: /src
    command: /bin/bash -c "bin/bash"
    #command: /bin/bash -c "dotnet restore ./WebApplication1.sln && dotnet publish ./WebApplication1.sln -c Release -o ./obj/Docker/publish"
