version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    environment:
      - DOCKER_HOST=127.0.0.1:80
    volumes:
      - .:/src
    working_dir: /var/jenkins_home/workspace/WebApplication1
    command: /bin/bash -c "dotnet restore ./WebApplication1.sln && dotnet publish ./WebApplication1.sln -c Release -o ./obj/Docker/publish"
