version: '3'

services:
  webapplication1:
    image: registry.gitlab.com/pdouelle/webapplication1
    environment:
      - VIRTUAL_HOST=dichotomiedev.hopto.org
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile